### ISSUE TITLE
Launch error -1 due to compatibility issue with eatinganimations mod when loaded with dependency groovymodloader

### ISSUE THREAD

**Issue by GITHUBFIXUREMAILCODE** [ValkyrienSkies/Valkyrien-Skies-2#767] opened 2024-03-17 13:27 UTC
### Mod Name

eatinganimations  and groovymodloader

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Opens loading screen, the sends back to launcher

### Issue reproduction

have eatinganimations ver 5.0.0 and gml 4.0.9

### Logs

[09:26:05] [main/INFO]: ModLauncher running: args [--username, AZ09XO, --version, forge-47.2.20, --gameDir, C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat, --assetsDir, C:\Users\Anthony N\curseforge\minecraft\Install\assets, --assetIndex, 5, --uuid, bed5cb17c3d848ffa0d9365e54e1c94e, --accessToken, ????????, --clientId, NzVmZWJkMmYtNDRhZS00ZGZmLTg0YjktODYxYzVmZTNkNjNl, --xuid, 2535435440245503, --userType, msa, --versionType, release, --width, 1024, --height, 768, --quickPlayPath, C:\Users\Anthony N\curseforge\minecraft\Install\quickPlay\java\1710681963909.json, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.20, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[09:26:05] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8 by Microsoft; OS Windows 11 arch amd64 version 10.0
[09:26:05] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[09:26:05] [main/INFO]: Trying GL version 4.6
[09:26:06] [main/INFO]: Requested GL version 4.6 got version 4.6
[09:26:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Anthony%20N/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23100!/ Service=ModLauncher Env=CLIENT
[09:26:06] [pool-2-thread-1/INFO]: GL info: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.13, NVIDIA Corporation
[09:26:06] [main/INFO]: Found mod file architectury-9.2.14-forge.jar of type MOD with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file create-1.20.1-0.5.1.f.jar of type MOD with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file create-stuff-additions1.20.1_v2.0.4a.jar of type MOD with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file create_interactive-1201-forge-1.0.2-beta.1.jar of type MOD with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file createaddition-1.20.1-1.2.3.jar of type MOD with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file createbigcannons-forge-1.20.1-0.5.3.b.jar of type MOD with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file CreativeCore_FORGE_v2.11.24_mc1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file eatinganimation-1.20-5.0.0.jar of type MOD with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file gml-4.0.9-all.jar of type LANGPROVIDER with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file Iceberg-1.20.1-forge-1.1.21.jar of type MOD with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file kotlinforforge-4.10.0-all.jar of type LIBRARY with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file monolib-forge-1.20.1-1.0.0.jar of type MOD with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file moonlight-1.20-2.11.2-forge.jar of type MOD with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/INFO]: Found mod file valkyrienskies-120-2.1.3-beta.1.jar of type MOD with provider {mods folder locator at C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods}
[09:26:06] [main/WARN]: Mod file C:\Users\Anthony N\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.20.1-47.2.20\fmlcore-1.20.1-47.2.20.jar is missing mods.toml file
[09:26:06] [main/WARN]: Mod file C:\Users\Anthony N\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.2.20\javafmllanguage-1.20.1-47.2.20.jar is missing mods.toml file
[09:26:06] [main/WARN]: Mod file C:\Users\Anthony N\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.2.20\lowcodelanguage-1.20.1-47.2.20.jar is missing mods.toml file
[09:26:06] [main/WARN]: Mod file C:\Users\Anthony N\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.20.1-47.2.20\mclanguage-1.20.1-47.2.20.jar is missing mods.toml file
[09:26:06] [main/INFO]: Found mod file fmlcore-1.20.1-47.2.20.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@629f066f
[09:26:06] [main/INFO]: Found mod file javafmllanguage-1.20.1-47.2.20.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@629f066f
[09:26:06] [main/INFO]: Found mod file lowcodelanguage-1.20.1-47.2.20.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@629f066f
[09:26:06] [main/INFO]: Found mod file mclanguage-1.20.1-47.2.20.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@629f066f
[09:26:06] [main/INFO]: Found mod file client-1.20.1-20230612.114412-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@629f066f
[09:26:06] [main/INFO]: Found mod file forge-1.20.1-47.2.20-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@629f066f
[09:26:07] [main/INFO]: Found 49 dependencies adding them to mods collection
[09:26:07] [main/INFO]: Found mod file jackson-dataformat-toml-2.15.2.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file classmate-1.5.1.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-json-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file srgutils-0.5.4.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-macro-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file mod-4.0.9.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file joml-primitives-1.10.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file json-schema-validator-1.0.71.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file jackson-module-parameter-names-2.14.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file Registrate-MC1.20-1.3.3.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file jackson-kotlin-dsl-1.2.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file zjsonpatch-0.4.11.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file api-1.1.0+b19b27c4a4.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file jackson-dataformat-cbor-2.14.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file javax.inject-1.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file util-1.1.0+b19b27c4a4.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file jackson-annotations-2.15.2.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file jackson-module-kotlin-2.14.0-rubyfork.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file script-mods-4.0.9-all.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file kffmod-4.10.0.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file jackson-core-2.15.2.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file flywheel-forge-1.20.1-0.6.10-7.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-typecheckers-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-templates-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-fat-4.0.9.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file cgl-1.20-forge-0.3.3.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file ritchiesprojectilelib-1.0.0-369e88d+1.20.1-forge.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-nio-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-dateutil-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file commons-collections4-4.3.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-xml-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-toml-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file mixinextras-forge-0.2.1-beta.2.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file jackson-databind-2.15.2.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-macro-library-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file MixinExtras-0.2.1-beta.2.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file jsonschema-module-jackson-4.25.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file itu-1.7.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-ginq-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-contracts-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file kfflang-4.10.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file jsonschema-generator-4.25.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file jankson-1.2.2.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file cloth-config-forge-11.1.106.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file dagger-2.43.2.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file kfflib-4.10.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file commons-math3-3.6.1.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Found mod file groovy-datetime-4.0.13.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@40712ee9
[09:26:07] [main/INFO]: Starting runtime mappings setup...
[09:26:07] [main/INFO]: Injecting ScriptModLocator candidates...
[09:26:07] [main/INFO]: Injected Jimfs file system
[09:26:07] [main/INFO]: Skipped loading script mods from directory C:\Users\Anthony N\curseforge\minecraft\Instances\Valkmodcompat\mods\scripts as it did not exist.
[09:26:07] [main/INFO]: Injected ScriptModLocator mod candidates. Found 0 valid mod candidates and 0 broken mod files.
[09:26:09] [GML Mappings Thread/INFO]: Loaded runtime mappings in 1614ms
[09:26:09] [GML Mappings Thread/INFO]: Finished runtime mappings setup.

**Comment by GITHUBFIXUREMAILCODE** [comment] 2024-03-17 13:55
Here is the current mod list:
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/148289201/df288e73-8109-4d72-b034-463657d38d41)

**Comment by PriestOfFerns** [comment] 2024-03-17 16:11
does it work without VS2 and interactive

**Comment by GITHUBFIXUREMAILCODE** [comment] 2024-03-17 17:13
yes, it works without VS2 & interactive.

**Comment by Rubydesic** [comment] 2024-03-27 07:58
To help you with your crash I need some more information - please go to your .minecraft/logs folder and upload the "latest.log" and "debug.log" file.

**Comment by Rubydesic** [comment] 2024-03-29 18:17
Duplicate of #747

**Closed by Rubydesic** 2024-03-29 18:17 UTC
Labels: compat
