### ISSUE TITLE
[1.20.1][Forge] Crash when use Immersive Portals (Fabric) mod with Connector mod.

### ISSUE THREAD

**Issue by cmy2008** [ValkyrienSkies/Valkyrien-Skies-2#748] opened 2024-02-25 10:01 UTC
### Mod Name

Immersive Portals

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

NeoForge

### Issue description

Minecraft Version: 1.20.1
Mod Loader: NeoForge 47.1.100
Java Version: 21-ea

### Issue reproduction

Launch Game, then crash when loading mods.

### Logs

[minecraft-exported-crash-info-2024-02-25T17-49-18.zip](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14395926/minecraft-exported-crash-info-2024-02-25T17-49-18.zip)

**Comment by popcron** [comment] 2024-03-10 20:33
able to get it running with this setup in 1.20.1, only valk skies mod + create mod loaded
![image](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/23342532/0accca28-6f63-4b3a-a722-7bfc527c496d)
the version ahead for immersive portals fails, would be interesting to know what causes that

**Comment by Byllfighter** [comment] 2024-03-25 17:40
Same crash

**Comment by Rubydesic** [comment] 2024-03-27 08:07
Duplicate of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/330

**Closed by Rubydesic** 2024-03-27 08:07 UTC
Labels: compat
