### ISSUE TITLE
Leawind's third person rendering

### ISSUE THREAD

**Issue by Dassie123** [ValkyrienSkies/Valkyrien-Skies-2#1000] opened 2024-11-12 18:20 UTC
### Mod Name

Leawind's third person

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

When activating leawind's third person while in a ship my game bugs out and I only see space from starlance mod and my game freezes. I expect leawind's third person just to work like when you are not in a ship.

### Issue reproduction

Make a vs ship with a seat, get into the seat and activate third person. 
https://1drv.ms/v/s!AjZ_2hxgvegLgZRMRil6OPbPYUZpAw?e=AQbZA7
This a onedrive shared link showing my issue. The perspective shifting happens without me moving my mouse. And the few seconds it did look normal, my game freezed.

**Comment by thetheaplant** [comment] 2024-11-12 19:03
Duplicate of #766

**Closed by thetheaplant** 2024-11-12 19:03 UTC
Labels: compat
