### ISSUE TITLE
Incompatible with "Immersive Portals" [1.18.2 - forge and fabric both tested]

### ISSUE THREAD

**Issue by ExpertNugget** [ValkyrienSkies/Valkyrien-Skies-2#368] opened 2023-01-19 23:45 UTC
When both mods are installed the airships from "Eureka! Airships! (Forge/Fabric)" become invisible and no longer interactable, upon player collision of where a ship used to be causes player to become stuck.

Issue reported to both mods.

Fabric Logs:
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10461985/latest.log)
Forge Logs:
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10462001/latest.log)

Both logs taken after completing the same actions:
1) Create creative world (default settings)
2) Made basic airship
3) assembled (this causes the airship to become invisible)
4) exited world

**Comment by tt-thoma** [comment] 2023-03-07 20:31
Same issue here.

**Comment by TheUndeadOwlGoddess** [comment] 2023-06-06 23:49
Has there been any update on this issue?

**Comment by Rubydesic** [comment] 2024-03-27 08:06
Duplicate of #330

**Closed by Rubydesic** 2024-03-27 08:06 UTC

**Comment by Nightmar0** [comment] 2025-02-19 16:01
Um, did you turn off block-face culling in video settings? That might help.

**Comment by thetheaplant** [comment] 2025-02-19 16:03
Blockface culling is not related to the issue shown.

**Comment by Nightmar0** [comment] 2025-02-19 16:42
Yeh. UR right. I crashed in 1.18.2 without the game even loading. 🤣🤣
