### ISSUE TITLE
Can't start a swim in water on ships

### ISSUE THREAD

**Issue by AlexanderwithaA** [ValkyrienSkies/Valkyrien-Skies-2#791] opened 2024-03-31 01:16 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Fabric

### Issue description

Try to swim in water and you can't, you have to already be swimming to swim in water on ships.

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/101488091/e08bda63-fbff-40a6-8c18-3fdc35e5da2f

### Issue reproduction

1. make two boxes of water, one shipified
2. swim from the solid one to the ship
3. try to swim back, you can't start a swim

**Comment by thetheaplant** [comment] 2024-09-18 22:57
Duplicate of #536

**Closed by thetheaplant** 2024-09-18 22:57 UTC
Labels: bug
