### ISSUE TITLE
Compat issue with Tardis Refined

### ISSUE THREAD

**Issue by zz4163** [ValkyrienSkies/Valkyrien-Skies-2#956] opened 2024-09-05 03:18 UTC
### Mod Name

Tardis Refined

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

What happens: MC/Server Crashes when trying to use the shears on the fully grown tardis to try to enter it.
Expected: Enters the tardis after using the shears on the fully grown tardis.

If anyone know a temp fix to this, that would be great but it's not needed.

### Issue reproduction

Use the shears on the fully grown TT with VS and Tardis Refined installed.

### Logs

(in my case the server crashed and here's the link to the server crash report)
https://mclo.gs/h4j9EVQ

**Comment by thetheaplant** [comment] 2024-09-05 04:14
Duplicate of #641 and #504.

**Closed** 2024-09-18 19:59 UTC
Labels: compat
