### ISSUE TITLE
Incompatilibilty with Eatinganimations/GML

### ISSUE THREAD

**Issue by ToastiMan** [ValkyrienSkies/Valkyrien-Skies-2#786] opened 2024-03-29 15:12 UTC
### Mod Name

Eatinganimations/GroovyModLoader(GML)

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Tested with only these 3 mods in Neoforge, Game crashes without crashlog. Logs don't seem to help neither.

### Issue reproduction

Install these 3 mods, start minecraft -> Crash

### Logs

[2024-03-29-7.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14805610/2024-03-29-7.log)
[debug-1.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14805611/debug-1.log)

**Comment by Rubydesic** [comment] 2024-03-29 18:17
Duplicate of #747

**Closed by Rubydesic** 2024-03-29 18:17 UTC
Labels: compat
