### ISSUE TITLE
VS doesn't seem to work with the Vault mod

### ISSUE THREAD

**Issue by ninjomoe** [ValkyrienSkies/Valkyrien-Skies-2#405] opened 2023-02-02 20:35 UTC
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/10573251/latest.log)

**Comment by Rubydesic** [comment] 2023-05-27 06:21
dupe of #450

**Closed by Rubydesic** 2023-05-27 06:21 UTC
Labels: bug, compat
