### ISSUE TITLE
Valkyrien Skies not compatible with Farmer's Delight

### ISSUE THREAD

**Issue by RandomUser240306** [ValkyrienSkies/Valkyrien-Skies-2#420] opened 2023-02-17 04:36 UTC
Mods used: 
Create Astral modpack (latest version) + Valkyrien Skies 2 and Eureka Airships

How to recreate:
Place cooking pot in a vessel and assemble with ship helm. 

Issue:
Cooking pot breaks when ship is assembled, dropping any contents.

**Comment by Rubydesic** [comment] 2023-02-20 23:32
Duplicate of #418

**Closed by Rubydesic** 2023-02-20 23:32 UTC
