### ISSUE TITLE
Compat Issue with Embeddium 1.20.1

### ISSUE THREAD

**Issue by NitroStarman** [ValkyrienSkies/Valkyrien-Skies-2#656] opened 2023-12-22 03:53 UTC
### Mod Name

Embeddium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Minecraft crashes on load when any Sodium based fork mod and ValkyrienSkies is installed on Minecraft 1.20.1

### Issue reproduction

Install Embeddium or other Sodium based Forge forks like Rubidium.

### Logs

Crash log: [crash-2023-12-21_22.38.13-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13748126/crash-2023-12-21_22.38.13-client.txt)
Log file: [latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13748127/latest.log)

**Comment by Rubydesic** [comment] 2023-12-27 23:08
Duplicate of #580

**Closed by Rubydesic** 2023-12-27 23:08 UTC
Labels: compat
