### ISSUE TITLE
crash on launch with embeddium

### ISSUE THREAD

**Issue by eldritch-cookie** [ValkyrienSkies/Valkyrien-Skies-2#619] opened 2023-11-07 15:48 UTC
### Mod Name

embeddium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

game crashes on launch when eureka + valkiryien skies are installed with embeddium

### Issue reproduction

install the mods and try to launch game.

### Logs

[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13282924/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13282932/latest.log)

**Comment by JoelZBub** [comment] 2023-11-11 14:02
duplicate of #569 & #580 & #599 & #609

**Closed** 2023-12-27 23:09 UTC
Labels: compat
