### ISSUE TITLE
Breaks with tardis refined 

### ISSUE THREAD

**Issue by thesheriff1** [ValkyrienSkies/Valkyrien-Skies-2#641] opened 2023-12-02 17:48 UTC
### Mod Name

Tardis Refined 

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Fabric

### Issue description

The crash occurs when you enter the Tardis

### Issue reproduction

Enter the Tardis 

### Logs

https://pastebin.com/UaS1HkSc

**Comment by shadowedblue** [comment] 2024-09-06 09:46
+1

I worked around it by moving all my ships/valkyrien skies blocks into unloaded chunks, removing all Valkyrien skies mods, shear the Tardis roots, then adding back Valkyrien skies and I am able to enter/exit Tardis just fine.

**Comment by thetheaplant** [comment] 2024-09-23 03:23
Duplicate of #504

**Closed by thetheaplant** 2024-09-23 03:23 UTC
Labels: compat
