### ISSUE TITLE
Water on ships doesn't push entities correctly

### ISSUE THREAD

**Issue by AlexanderwithaA** [ValkyrienSkies/Valkyrien-Skies-2#630] opened 2023-11-23 23:36 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Fabric

### Issue description

Water on ships will push players relative to the world, so water going straight on a diagonal ship will push diagonally. Video for example.

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/101488091/5240c616-5998-4619-a29e-4cf320f175f1

### Issue reproduction

build a ship with flowing water on it. Turn the ship diagonal to the overworld and jump in the water. It will now push you diagonally..

**Comment by thetheaplant** [comment] 2024-09-18 22:59
Duplicate of #536

**Closed by thetheaplant** 2024-09-18 22:59 UTC
Labels: bug, good first issue
