### ISSUE TITLE
Water flows are stronger with VS installed

### ISSUE THREAD

**Issue by Zen9890** [ValkyrienSkies/Valkyrien-Skies-2#830] opened 2024-05-03 06:07 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

When VS is installed you cant run against waterflows, while in vanilla you can, this little change makes swimming in water that has any kind of flow extremely inconvenient

### Issue reproduction

1) install VS
2) try running against flowing water
3) uninstall VS and repeat step 2
4) Behaviour is vastly different

**Comment by soap-kid** [comment] 2024-05-12 03:33
Having the same issue on 1.20.1 version.

**Comment by DaftHunk** [comment] 2024-06-18 20:02
We also have this issue on forge 1.20.1

**Comment by thetheaplant** [comment] 2024-09-18 22:58
Duplicate of #536

**Closed by thetheaplant** 2024-09-18 22:58 UTC
Labels: bug
