### ISSUE TITLE
[1.18.2][Fabric] Dimensional Doors Compatibility

### ISSUE THREAD

**Issue by ryanhaney97** [ValkyrienSkies/Valkyrien-Skies-2#459] opened 2023-04-27 22:35 UTC
Currently, the Fabric version is incompatible with Dimensional Doors.

REASONING:
I would highly recommend that you make this a priority, as it could seriously increase usability: thanks to dimensional doors, ship interiors could be a separate dimension instead, allowing incompatible blocks to be placed there and greatly expanding options until compatibility is added for everything. And it should be relatively easy to add compatibility, at least compared to a similar solution like Immersive Portals, as there's no rendering tricks here.

PROBLEMS:
In the mod, when said dimensional doors are opened they reveal a "dimensional rift", that upon touching teleports you to a pocket dimension (and which can be used on the other end to teleport back).
The main compatibility problem is that these rifts have no collision on ships, so it is impossible to use them to get to the pocket dimension.
I also don't believe the NBT data of the doors is being copied properly when the ship is created or deconstructed, though I haven't tested this as much.

That should handle most of it, but my testing was limited since the portals themselves didn't work.

**Comment by Rubydesic** [comment] 2024-03-27 08:07
Duplicate of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/330

**Closed by Rubydesic** 2024-03-27 08:07 UTC
Labels: compat

**Comment by flashgnash** [comment] 2025-08-30 08:30
> Duplicate of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/330

Dimensional doors is not immersive portals. I'm running into the same issue with it now

The issue is the collision detection with the portal plane (not an immersive portals portal)
