### ISSUE TITLE
<title> non combatibility with terrafirmacraft

### ISSUE THREAD

**Issue by UnitedCreeper** [ValkyrienSkies/Valkyrien-Skies-2#858] opened 2024-05-31 11:45 UTC
### Mod Name

terrafirmacraft

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

i wanted to play with my fav mods so i created a modpack, played for an hour then got off, when i got back on it wasnt working, tried everything and it didnt work untill i turned off either terrafirmacraft or valkyrien skies, i went to the terrafirmacraft github and they said it possibly is an issue with how valk works with their rendering or somthing

### Issue reproduction

should be just put valkyrien skies in a modpack with terrafirmacraft ig

### Logs

[latest.log](https://github.com/user-attachments/files/15513037/latest.log)
[latest.log](https://github.com/user-attachments/files/15513037/latest.log)
[latest.log](https://github.com/user-attachments/files/15513037/latest.log)

**Comment by PriestOfFerns** [comment] 2024-06-04 06:08
duplicate of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/832 and https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/711

**Closed** 2024-09-18 21:26 UTC
Labels: compat
