### ISSUE TITLE
Compatibility issue with Pehkui

### ISSUE THREAD

**Issue by Xavienth** [ValkyrienSkies/Valkyrien-Skies-2#719] opened 2024-02-04 08:22 UTC
### Mod Name

Pehkui

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Pehkui allows you to set the physical scale of entities. When entities have a scale of greater than about 1.5 or 1.75 (specifically, when the motion attribute is higher than that), they rapidly accelerate on contact with walls. Relatedly, stepping up diagonal-stair patterns flings the entity hundreds of blocks in the air.

This behaviour is not observed with just Pehkui installed.

### Issue reproduction

Set your motion scale to 2 with /scale set pehkui:motion 2
Create a wall you cannot step over
Approach the wall at an oblique angle
Accelerate rapidly.

**Comment by thetheaplant** [comment] 2024-09-27 19:59
Duplicate of #507

**Closed by thetheaplant** 2024-09-27 19:59 UTC
Labels: compat
