### ISSUE TITLE
Game crashes when loading Valkyrien Skies with Embeddium

### ISSUE THREAD

**Issue by Amronos** [ValkyrienSkies/Valkyrien-Skies-2#580] opened 2023-09-24 04:26 UTC
### Mod Name

Embeddium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Minecraft crashes when loading Minecraft Forge 1.20.1 with Embeddium, Eureka, Valkyrien Skies, and Kotlin for Forge.

Expected Result: Minecraft should load properly.

### Issue reproduction

1. Load Minecraft Forge 1.20.1 with Embeddium, Eureka, Valkyrien Skies, and Kotlin for Forge
2. The Game Crashes

### Logs

[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12707783/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12707784/latest.log)

**Comment by embeddedt** [comment] 2023-09-24 14:16
This is caused by Valkyrien Skies using mixins into Sodium internals and will need to be fixed on your end. However I'm happy to discuss and provide suggestions for better compatibility without needing to rely on mixins, if possible.

**Comment by Amronos** [comment] 2023-09-24 16:14
ok, thanks

**Comment by JoelZBub** [comment] 2023-11-11 13:57
Duplicate of #569

**Comment by ewoudje** [comment] 2024-03-05 15:28
Closing in favor of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/556

**Closed by ewoudje** 2024-03-05 15:28 UTC
Labels: compat
