### ISSUE TITLE
Cannot move while crounching on a ship

### ISSUE THREAD

**Issue by THOMASS47** [ValkyrienSkies/Valkyrien-Skies-2#381] opened 2023-01-22 04:54 UTC
Title

Mods:
![image](https://user-images.githubusercontent.com/63131669/213901046-ed9a619a-4782-455f-937b-2192b95b0dc2.png)

Version:
![image](https://user-images.githubusercontent.com/63131669/213901087-439cb5d8-1224-4f7f-ba4c-da482a8ae16a.png)

**Comment by Rubydesic** [comment] 2023-04-18 04:23
Duplicate of #251

**Closed by Rubydesic** 2023-04-18 04:23 UTC
