### ISSUE TITLE
Minecraft server crash

### ISSUE THREAD

**Issue by Boor0n** [ValkyrienSkies/Valkyrien-Skies-2#691] opened 2024-01-13 14:29 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

It seems you have encountered an issue with the duration of a single server tick in Minecraft. The server tick should take no more than 0.05 seconds, but in your case, it took 60 seconds, triggering the ServerHangWatchdog, which detected that the server "hung" on one tick.

The error occurred within the Valkyrien Skies mod (valkyrienskies-1192-2.2.0-beta.3.jar), specifically in the method VSPhysicsPipelineStage.pushGameFrame.

### Issue reproduction

i don't now

### Logs

[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13928305/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13928306/latest.log)

**Comment by thetheaplant** [comment] 2024-09-19 00:17
Duplicate of #323

**Closed by thetheaplant** 2024-09-19 00:17 UTC
Labels: bug
