### ISSUE TITLE
VS2 and Epic Fight Compat issues

### ISSUE THREAD

**Issue by ZhiChro** [ValkyrienSkies/Valkyrien-Skies-2#934] opened 2024-08-06 13:29 UTC
### Mod Name

Epic Fight

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Whenever I do certain attacks with epic fight like a sprint attack, demolition leap, and meteor slam the game would crash.

### Issue reproduction

Install epic fight together with VS2, in game the best weapon to use would be a greatsword from epic fight, equip it and sprint then attack, it should crash before you can even finish the animation.

**Comment by thetheaplant** [comment] 2024-09-22 21:29
Duplicate of #805

**Closed** 2024-09-23 02:23 UTC
Labels: compat
