### ISSUE TITLE
Bug with rendering moving textures of blocks on Eureka ships

### ISSUE THREAD

**Issue by vlad1m** [ValkyrienSkies/Valkyrien-Skies-2#652] opened 2023-12-16 23:05 UTC
### Mod Name

Embeddium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

When certain blocks,like the globe from ,,supplimentaries,, or the helm from ,,Eureka ships,, ,are placed on the ship and assembled the part of their texture that moves will disappear.

### Issue reproduction

Install the ,,Embeddium,, ,,Supplimentaries,, and ,,Eureka ships,, mods, enter a world, create and assemble a ship with the mentioned blocks.

**Comment by Rubydesic** [comment] 2023-12-27 23:08
Duplicate of #580

**Closed by Rubydesic** 2023-12-27 23:08 UTC
Labels: compat
