### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by kaka34665** [ValkyrienSkies/Valkyrien-Skies-2#999] opened 2024-11-09 15:40 UTC
### Mod Name

Groovy Mod Loader

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

When I include the Groovy Mod Loader (gml) in my mod list where I have the Valkrein skies mod, the game crashes and it takes me back to the minecraft launcher upon loading in. Why do I want it fixed? Because the Eating Animations mod requires this mod loader, and this mod is really cool. What I expect is simply minecraft not crashing when I have both of these mods.

### Issue reproduction

Step 1: Get Valkrein skies
Step 2: Get Groovy Mod Loader

### Logs

[debug.log](https://github.com/user-attachments/files/17688504/debug.log)
[latest.log](https://github.com/user-attachments/files/17688505/latest.log)

**Comment by thetheaplant** [comment] 2024-11-09 15:47
Duplicate of #747

**Closed by thetheaplant** 2024-11-09 15:47 UTC
Labels: compat
