### ISSUE TITLE
[1.20.1/Fabric] Incompatible with Sodium version needed for Immersive Portals

### ISSUE THREAD

**Issue by Flexico** [ValkyrienSkies/Valkyrien-Skies-2#784] opened 2024-03-28 17:23 UTC
### Mod Name

Immersive Portals

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

The latest version of Valkyrien Skies requires the use of Sodium 0.5.8 or later, but I also have Immersive Portals,which needs Sodium 0.5.3 and Indium 1.0.27; VS2 needs the latest versions. As far as I can tell I can't use both VS2 and IP.

### Issue reproduction

Download Valkyrien Skies, Immersive Portals, and their dependencies; install them to a Minecraft instance of 1.20.1 and Fabric. No matter what version combinations you choose, they won't be completely compatible.

**Comment by Rubydesic** [comment] 2024-03-29 18:19
Duplicate of #330

**Closed by Rubydesic** 2024-03-29 18:19 UTC
Labels: compat

**Comment by Flexico** [comment] 2024-03-29 20:56
Craaaaap.
