### ISSUE TITLE
Constant server crashes

### ISSUE THREAD

**Issue by Wafaloma** [ValkyrienSkies/Valkyrien-Skies-2#579] opened 2023-09-18 21:38 UTC
### Mod Name

Couldn't find

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

My moded server's console is spamed with "[Server thread/WARN] [or.va.co.im.pi.VSPhysicsPipelineStage/]: Too many game frames in the game frame queue. Is the physics stage broken?" with not long after the server crashing.
There is no such issue with only Valkyrien Skies and Eureka installed, but I failed to find any other mod that is causing it.
It also works fine in offline words.

### Issue reproduction

After entering any dimension/ getting teleported a long distance (as after respawning)/ disconecting from the server.

### Logs

[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12653595/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12653597/latest.log)
For clarification:
This logs are of the latest crash that was caused by disconecting from the sever.

**Comment by DizzyPrime** [comment] 2023-10-23 12:13
Having a similar issue, did removing Valkryrien Skies fix it?

**Comment by StewStrong** [comment] 2023-10-23 12:35
We'll have a fix for this behavior soonish.

**Comment by ajh123** [comment] 2023-12-24 17:24
Same problem for me in 1.20.1 Forge 47.2.0

**My logs**

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13762435/latest.log)

[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13762436/debug.log)

**Comment by thetheaplant** [comment] 2024-09-18 23:29
Related to #323, closing.

**Closed by thetheaplant** 2024-09-18 23:29 UTC
Labels: compat

**Comment by Rubydesic** [comment] 2024-09-19 00:08
Duplicate of #323
