### ISSUE TITLE
CTD when trying to use tree fertilizer from Create

### ISSUE THREAD

**Issue by sprocketaudio** [ValkyrienSkies/Valkyrien-Skies-2#725] opened 2024-02-09 21:10 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

Crash to desktop when you try to use tree fertilizer from create on a tree.

### Issue reproduction

Install create and VS and try to use tree fertilizer on a tree.

VS 2.1.2 beta1
create 0.5.1f

### Logs

[crash-2024-02-09_21.09.11-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14226352/crash-2024-02-09_21.09.11-server.txt)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14226354/latest.log)

**Comment by Victorakaerj** [comment] 2024-02-10 15:42
I also get that. Game freezes and crashes at around 2-3 times used on a sapling.

**Comment by TheLemon27** [comment] 2024-09-15 01:13
iirc, VS2 crashes when new dimensions are generated, and the way tree fertilizer is coded, it makes a brand new dimension for some reason. and thus, it crashes.

**Comment by thetheaplant** [comment] 2024-09-23 02:29
Duplicate of #679

**Closed by thetheaplant** 2024-09-23 02:29 UTC
Labels: bug
