### ISSUE TITLE
Mobs and players can go down bubble columns

### ISSUE THREAD

**Issue by Ricewaffel** [ValkyrienSkies/Valkyrien-Skies-2#871] opened 2024-06-13 15:20 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

Players and undead mobs can ignore water columns. I think players are fine but it breaks many farms that use bubble elevators to move mobs.

### Issue reproduction

Put zombies or skeletons in a bubble elevator and after a few seconds they will go down

**Comment by monty58** [comment] 2024-07-16 05:15
I'm seeing this in 1.19. It looks like is has something to do with overlapping hitboxes

**Comment by thetheaplant** [comment] 2024-09-18 22:57
Duplicate of #536, water borked.

**Closed by thetheaplant** 2024-09-18 22:57 UTC
Labels: bug
