### ISSUE TITLE
Valkyrien skies problem with rubidium

### ISSUE THREAD

**Issue by HyperFoxOne** [ValkyrienSkies/Valkyrien-Skies-2#569] opened 2023-08-31 13:06 UTC
### Mod Name

rubidium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

when I try to start minecraft with my modpack it does not work and if I remove either rubidium or valkyrien skies it works again

### Issue reproduction

use the same mods

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12486370/latest.log)

[crash-2023-08-31_15.05.11-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12486372/crash-2023-08-31_15.05.11-client.txt)

[launcher_log5.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12486373/launcher_log5.txt)

**Comment by SuperSpaceEye** [comment] 2023-08-31 15:39
use rubidium <0.7

**Comment by JoelZBub** [comment] 2023-11-11 14:05
Duplicate of #556

**Comment by ewoudje** [comment] 2024-03-05 15:28
Closing in favor of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/556

**Closed by ewoudje** 2024-03-05 15:28 UTC
Labels: compat
