### ISSUE TITLE
Bug occurs in Create Mod when Valkerien Skies is installed

### ISSUE THREAD

**Issue by Philemonzz** [ValkyrienSkies/Valkyrien-Skies-2#950] opened 2024-08-28 13:03 UTC
### Mod Name

Create

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Whenever items are blown into a funnel (using a fan) not all the items are picked up by the funnel and a few are left behind. I've found this only happens when the mod Valkerian Skies is also installed.

![2024-08-27_18 43 11](https://github.com/user-attachments/assets/15de1386-ac4a-43bd-acbb-7d50ba9d06c8)
In this image you can (slightly) see there's flint in the pile of gravel being washed, while the funnel has a filter allowing iron nuggets and flint through.

### Issue reproduction

To replicate, place a fan blowing through water so it can wash items. a couple blocks in the direction of the fan place a vault/chest with a brass funnel equipped with a filter (flint and/or nuggets). Now drop a couple stacks of gravel in the airstream so it gets washed. Once it converts into flint and nuggets some items should be left behind without entering the funnel.

**Comment by thetheaplant** [comment] 2024-08-28 14:27
Please read previous issues, duplicate of #554, #688, and #867. Please close this issue.

**Closed** 2024-08-28 16:11 UTC
Labels: compat
