### ISSUE TITLE
Game crashes during mod loading

### ISSUE THREAD

**Issue by phoenixborn635** [ValkyrienSkies/Valkyrien-Skies-2#609] opened 2023-10-26 18:09 UTC
### Mod Name

Rubidium, Embeddium, Sodium (fabric)

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [ ] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

The 3 mods i listed were all tested seperately and Sodium was tested on forge with Sinytra Connector. I had first put Rubidium in a modpack I made but it was crashing due to Valkerian Skies. At which point I had moved all respective mods to their own packs on curseforge with just Valkerian Skies and other mods listed below in the reproduction section. All 3 have similar crash reports and curseforge support has advised me to report the crashes here.

### Issue reproduction

Valkerian Skies, Eureka Airships (still crashes without), in a pack with Rubidium or Embeddium and it will crash with similar issues during the mod loading stage on forge. For sodium, Also Valkerian Skies and Eureka Airships but also Sinytra Connector and Connector Extras all on forge (Sinytra Connector has no known issues with Sodium as far as I'm aware). Sodium has the same crash issue as the other 2 though.

### Logs

Couldn't find the debug.log for any of these but I do have the latest
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13181102/latest.log) Rubidium
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13181118/latest.log) Embeddium
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13181185/latest.log) Sodium

**Comment by PriestOfFerns** [comment] 2023-10-26 23:21
Known issue, >0.5 versions of sodium are incompatible. Since Embeddium and Rubidium are ports of sodium, newer versions of them naturally suffer the same fate

**Comment by JoelZBub** [comment] 2023-11-11 14:01
duplicate of #569 & #580 & #599

**Closed** 2023-12-27 23:09 UTC
Labels: compat
