### ISSUE TITLE
cant move

### ISSUE THREAD

**Issue by potter1402** [ValkyrienSkies/Valkyrien-Skies-2#527] opened 2023-07-10 07:58 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Fabric

### Issue description

Movement inputs don't work, however you can teleport using endear pearls the issue occurs only on servers, but the server doesn't have to be modded after uninstalling the mod the issue disappears

### Issue reproduction

Log onto a server with the mod on

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11999225/latest.log)

**Comment by TheKidThatCodes** [comment] 2023-07-10 20:31
dupe of #526

**Comment by sheepman4267** [comment] 2023-07-15 04:55
@potter1402 Are you sure you had the mod installed on the server correctly? I found this bug because I was having this issue, but it turned out that the server didn't actually have the mod installed. Once I installed the mod on the server as well as the client, everything worked perfectly.

Since Valkyrien Skies changes so much of the physics engine in the game, I'm not really surprised that movement doesn't work if the mod is only on the client.

**Comment by thetheaplant** [comment] 2024-09-23 03:22
Unable to recreate, reportedly can be caused by tick suppression mods.

**Closed by thetheaplant** 2024-09-23 03:22 UTC
Labels: bug

**Comment by catlovelia** [comment] 2025-02-24 00:29
Ive spent 2 weeks trying to fix this... the mod wasnt on the server... its fixed now XD

**Comment by SisiMiring** [comment] 2025-06-08 14:03
how to fix it?
