### ISSUE TITLE
crash when placing a vertical slab from double slabs

### ISSUE THREAD

**Issue by veccyboi** [ValkyrienSkies/Valkyrien-Skies-2#881] opened 2024-06-25 23:05 UTC
### Mod Name

https://www.curseforge.com/minecraft/mc-mods/double-slabs

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [x] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

i added valkyrien skies, eureka, cc-vs, and clockwork to a 278-mod modpack on forge 40.2.14, and when trying to place a vertical slab as added by the double slabs mod at (https://www.curseforge.com/minecraft/mc-mods/double-slabs), the game crashed after the slab was placed: 
[crash-2024-06-25_17.47.07-server.txt](https://github.com/user-attachments/files/15980238/crash-2024-06-25_17.47.07-server.txt)

so I tried to replicate the issue with just valkyrien skies, eureka, kotlin for forge, and the double slabs mod and got what I think is the same crash: 
[crash-2024-06-25_18.03.18-server.txt](https://github.com/user-attachments/files/15980250/crash-2024-06-25_18.03.18-server.txt)
(full list of mods and their versions can be found in the crash reports IIRC)

the world will also never load with the vertical slab placed unless valkyrien skies and all its addons are removed or disabled.

### Issue reproduction

1. have valkyrien skies and double slabs installed
2. try to place a vertical slab from double slabs
3. the game crashes (i think the issue has to do with the lighting engine but I'm not sure)

### Logs

from the large modpack: 
[latest.log](https://github.com/user-attachments/files/15980218/latest.log)
[debug.log](https://github.com/user-attachments/files/15980219/debug.log)
with just the problem mods isolated:
[latest.log](https://github.com/user-attachments/files/15980261/latest.log)
[debug.log](https://github.com/user-attachments/files/15980262/debug.log)

**Comment by thetheaplant** [comment] 2024-09-23 17:18
Duplicate of #659

**Closed by thetheaplant** 2024-09-23 17:18 UTC
Labels: compat
