### ISSUE TITLE
Unable to swim again water currents in the 1.19 and 1.20 Forge versions.

### ISSUE THREAD

**Issue by soap-kid** [ValkyrienSkies/Valkyrien-Skies-2#822] opened 2024-04-25 06:27 UTC
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

In the latest **1.19.2** and **1.20.1** Forge versions of Valkyrien Skies, players are unable to swim again flowing water currents. I've been told this issue does *not* occur in the **1.18.2** versions, but have not verified this myself.

Attached below are examples of the same action being taken on differing 1.20.1 installs.

### Vanilla
![Vanilla](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/64805768/5ae031c1-df99-4969-a3e4-9c02c6cd9ce0)
-
### Forge *only*
![Forge](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/64805768/59fd72fc-98ae-41c4-9d7f-93e52d1a64e4)
-
### Forge with Valkyrien Skies
![VS](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/64805768/d53d71a2-3965-4ea4-b8ba-caaa1bde14bf)

### Issue reproduction

Find or create a flowing water current, try to move against it.

**Comment by FatherSarge** [comment] 2024-05-12 13:10
+1 also experiencing this

**Comment by GoobertFroobert** [comment] 2024-06-26 03:11
+1, thought it was some immersion mod I downloaded or something. Weird bug.

**Comment by Agent312** [comment] 2024-07-22 13:46
+1 I'm also experiencing it. It does occur in 1.18.2 (I'm currently on the version of forge 1.18.2 40.2.21

**Comment by thetheaplant** [comment] 2024-09-18 22:58
Duplicate of #536

**Closed by thetheaplant** 2024-09-18 22:58 UTC
Labels: bug
