### ISSUE TITLE
Incompatible with Sodium, even with Indium.

### ISSUE THREAD

**Issue by Lolothepro** [ValkyrienSkies/Valkyrien-Skies-2#135] opened 2022-08-04 15:43 UTC
[crash-2022-08-04_17.43.05-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/9261081/crash-2022-08-04_17.43.05-client.txt)

**Comment by Rubydesic** [comment] 2022-08-14 13:42
Duplicate of #78. Please don't open compat issues.

**Closed by Rubydesic** 2022-08-14 13:42 UTC
Labels: compat
